experiment:
  dataset: ncf_pinterest
  data_config:
    strategy: fixed
    train_path: ../data/{0}/pinterest-20.train.rating
    test_path: ../data/{0}/pinterest-20.test.rating
  binarize: True
  negative_sampling:
    strategy: fixed
    files: [ "<data_path>/pinterest-20.test.negative" ]
  top_k: 10
  evaluation:
    cutoffs: 10
    simple_metrics: [HR, nDCG]
  gpu: 0
  external_models_path: ../external/models/__init__.py
  models:
    external.RP3beta:
      meta:
        verbose: True
        save_recs: True
      neighborhood: 1000
      alpha: 0.8616
      beta: 0.4255
      normalize_similarity: True
