experiment:
  dataset: ncf_pinterest
  data_config:
    strategy: fixed
    train_path: ../data/{0}/pinterest-20.train.rating
    test_path: ../data/{0}/pinterest-20.test.rating
  binarize: True
  negative_sampling:
    strategy: fixed
    files: [ "<data_path>/pinterest-20.test.negative" ]
  top_k: 10
  evaluation:
    cutoffs: 10
    simple_metrics: [HR]
  gpu: 0
  external_models_path: ../external/models/__init__.py
  models:
    external.MostPop:
      meta:
        verbose: True
        save_recs: True
    external.RendleMF
      meta:
        hyper_max_evals: 1
        hyper_opt_alg: tpe
        validation_rate: 1
        verbose: True
        save_recs: True
      epochs: 256
      factors: 32
      lr: 0.007
      reg: 0.01
      m: 10
      random_seed: 42
    external.NeuMF:
      meta:
        hyper_max_evals: 1
        hyper_opt_alg: tpe
        verbose: True
        save_recs: True
        validation_rate: 1
      mf_factors: 64
      dropout: 0
      is_mf_train: True
      is_mlp_train: True
      batch_size: 256
      epochs: 100
      lr: 0.001
      m: 4
    Slim:
      meta:
        verbose: True
        save_recs: True
      l1_ratio: 1.15e-04
      alpha: 0.0526
      neighborhood: 1000
    external.iALS:
      meta:
        verbose: True
        save_recs: True
      factors: 30
      alpha: 50
      epsilon: 0.0010
      reg: 1.00e-02
      scaling: linear
      epochs: 45
    external.EASER:
      meta:
        verbose: True
        save_recs: True
        hyper_max_evals: 1
        hyper_opt_alg: tpe
      l2_norm: 3540
    external.RP3beta:
      meta:
        verbose: True
        save_recs: True
      neighborhood: 1000
      alpha: 0.8616
      beta: 0.4255
      normalize_similarity: True
    PureSVD:
      meta:
        verbose: True
        save_recs: True
      factors: 50
      seed: 42
