experiment:
  dataset: ncf_ml1m
  data_config:
    strategy: fixed
    train_path: ../data/{0}/ml-1m.train.rating
    test_path: ../data/{0}/ml-1m.test.rating
  binarize: True
  negative_sampling:
    strategy: fixed
    files: [ "<data_path>/ml-1m.test.negative" ]
  top_k: 10
  evaluation:
    cutoffs: 10
    simple_metrics: [HR]
  gpu: 0
  external_models_path: ../external/models/__init__.py
  models:
    external.MostPop:
      meta:
        verbose: True
        save_recs: True
    external.RendleMF:
      meta:
        validation_rate: 1
        verbose: True
        save_recs: True
      epochs: 256 
      factors: 32
      lr: 0.002
      reg: 0.005
      m: 8
      random_seed: 42
    external.NeuMF:
      meta:
        verbose: True
        save_recs: True
        validation_rate: 1
      mf_factors:  16
      dropout: 0
      is_mf_train: True
      is_mlp_train: True
      batch_size: 256
      epochs: 100
      lr: 0.001
      m: 4
    Slim:
      meta:
        verbose: True
        save_recs: True
      l1_ratio: 0.0000119
      alpha: 0.0788
      neighborhood: 544
    external.iALS:
      meta:
        verbose: True
        save_recs: True
      factors: 46
      alpha: 50
      epsilon: 10
      reg: 0.00001
      scaling: log
      epochs: 20
    external.EASER:
      meta:
        verbose: True
        save_recs: True
      l2_norm: 1320
    external.RP3beta: #from TOIS
      meta:
        verbose: True
        save_recs: True
      neighborhood: 546
      alpha: 1.0807
      beta: 0.7029
      normalize_similarity: True
    PureSVD:
      meta:
        verbose: True
        save_recs: True
      factors: 52
      seed: 42
