experiment:
  data_config:
    strategy: fixed
    dataloader: KnowledgeChainsLoader
#    dataloader: DataSetLoader
#    dataset_path: ../data/{0}/trainingset.tsv
#    root_folder: ../data/{0}/splitting/
    train_path: ../data/{0}/trainingset.tsv
#    validation_path: ../data/{0}/trainingset.tsv
    test_path: ../data/{0}/testset.tsv
    side_information:
        feature_data: ../data/{0}/original/features.npy
        map: ../data/{0}/map.tsv
        features: ../data/{0}/features.tsv
        properties: ../data/{0}/properties.conf
#  splitting:
##    save_on_disk: True
##    save_folder: ../data/{0}/splitting/
#    test_splitting:
#        strategy: random_subsampling
#        leave_n_out: 1
#        folds: 1
#    validation_splitting:
#        strategy: fixed_timestamp|temporal_hold_out|random_subsampling|random_cross_validation
#        timestamp: best|1609786061
#        test_ratio: 0.2
#        leave_n_out: 1
#        folds: 5
#  prefiltering:
#    strategy: global_threshold
#    threshold: 0
#    core: 5
#    rounds: 2
  dataset: categorical_dbpedia_ml1m
#  dataset: example
  path_output_rec_result: ../results/{0}/recs/
  path_output_rec_weight: ../results/{0}/weights/
  path_output_rec_performance: ../results/{0}/performance/
  path_logger_config: ./config/logger_config.yml
  path_log_folder: ../log/
  top_k: 50
  evaluation:
    cutoff: 10
    simple_metrics: [ nDCG, Precision, Recall, ItemCoverage, HR, MRR, MAP, F1, Gini, SEntropy, EFD, EPC, LAUC]
#    cutoff: 50
    relevance_threshold: 1
    paired_ttest: True
    complex_metrics:
    - metric: UserMADrating
      clustering_name: Happiness
      clustering_file: /home/cheggynho/Documents/UMUAI2019FatRec/ml-1m-2020-03-08/Clusterings/UsersClusterings/user_clustering_happiness.tsv
    - metric: DSC
      beta: 2
    - metric: SRecall
      feature_data: ../data/categorical_dbpedia_ml1m/map.tsv
#    - metric: UserMADrating
#      clustering_name: Happiness
#      clustering_file: /home/cheggynho/Documents/UMUAI2019FatRec/ml-1m-2020-03-08/Clusterings/UsersClusterings/user_clustering_happiness.tsv
#    - name: alpha_ndcg
#        alpha: 0.2
#      - name: IELD
#        content_file: path
  gpu: -1 # -1 is not use GPU
  models:
#    Random:
#      meta:
#        save_recs: True
#    MultiDAE:
#      meta:
#        hyper_max_evals: 1
#        hyper_opt_alg: tpe
#        validation_rate: 10
#        verbose: False
#        save_weights: False
#        save_recs: True
#      lr: 0.001
#      epochs: 50
#      intermediate_dim: 600
#      latent_dim: 200
#      batch_size: -1
#      dropout_pkeep: 1
#      reg_lambda: 0.01
    MultiVAE:
      meta:
        hyper_max_evals: 2
        hyper_opt_alg: tpe
        validation_rate: 10
        verbose: False
        save_weights: False
        save_recs: False
      lr: 0.01
      epochs: [50,20]
      intermediate_dim: 300
      latent_dim: 100
      batch_size: -1
      dropout_pkeep: 1
      reg_lambda: 0.01
#    BPRMF:
#      meta:
#        hyper_max_evals: 10
#        hyper_opt_alg: tpe
#        validation_rate: 10
#        verbose: True
#        save_weights: False
#        save_recs: True
#        validation_metric: nDCG
#        restore_epoch: -1
#      lr: 0.05
#      epochs: 50
#      embed_k: [10,50,100,125,150,200]
#      bias_regularization: 0
#      user_regularization: [0.0025,0.005,0.01]
#      positive_item_regularization: [0.0025,0.005,0.01]
#      negative_item_regularization: [0.00025,0.0005,0.001]
#      update_negative_item_factors: True
#      update_users: True
#      update_items: True
#      update_bias: True
#    NNBPRMF:
#      meta:
#        hyper_max_evals: 10
#        hyper_opt_alg: tpe
#        validation_rate: 10
#        verbose: True
#        save_weights: False
#        save_recs: True
#        validation_metric: nDCG
#        restore_epoch: -1
#      lr: [0.001]
#      epochs: 50
#      embed_k: [50,100,125,150,200]
#      batch_size: 512
#      l_w: 0.0025
#      l_b: 0
#    VBPR:
#      meta:
#        verbose: 1
#        save_weights: True
#        save_recs: True
#        validation_metric: nDCG
#        restore_epoch: -1
#      lr: 0.005
#      epochs: 20
#      embed_k: 100
#      embed_d: 20
#      batch_size: 128
#      l_w: 0.000025
#      l_b: 0
#      l_e: 0.002
#    KaHFM:
#      meta:
#        hyper_max_evals: 1
#        hyper_opt_alg: tpe
#        validation_rate: 1
#        verbose: True
#        save_weights: False
#        save_recs: True
#        validation_metric: nDCG
#        restore_epoch: -1
#      lr: 0.05
#      epochs: 10
#      bias_regularization: 0
#      user_regularization: 0.0025
#      positive_item_regularization: 0.0025
#      negative_item_regularization: 0.00025
#      update_negative_item_factors: True
#      update_users: True
#      update_items: True
#      update_bias: True
#    KaHFMBatch:
#      meta:
#        hyper_max_evals: 5
#        hyper_opt_alg: tpe
#        validation_rate: 10
#        verbose: False
#        save_weights: False
#        save_recs: False
#        validation_metric: nDCG
#        restore_epoch: -1
#      lr: [0.001, 0.0005, 0.0001]
#      epochs: 100
#      batch_size: [512,1024, 2048]
#      l_w: [0.0025, 0.005]
#      l_b: 0
#    NGCF:
#      meta:
#        hyper_max_evals: 1
#        hyper_opt_alg: tpe
#        validation_rate: 10
#        verbose: True
#        save_weights: True
#        save_recs: True
#      learning_rate: 0.1
#      epochs: 100
#      embed_k: 64
#      l_w: 0.001
#      weight_size: (64,)
#      batch_size: 128
#      node_dropout: ()
#      message_dropout: (0.1,)
#      n_fold: 5